<?php

namespace Proxies\__CG__\QuejasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cliente extends \QuejasBundle\Entity\Cliente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'ci', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'nombre', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'apellidos', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'calle', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'entre', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'apartamento', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'edificio', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'casa', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'telefonos', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'correo', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'empresa', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'municipio');
        }

        return array('__isInitialized__', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'ci', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'nombre', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'apellidos', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'calle', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'entre', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'apartamento', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'edificio', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'casa', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'telefonos', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'correo', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'empresa', '' . "\0" . 'QuejasBundle\\Entity\\Cliente' . "\0" . 'municipio');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cliente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCi($ci)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCi', array($ci));

        return parent::setCi($ci);
    }

    /**
     * {@inheritDoc}
     */
    public function getCi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCi', array());

        return parent::getCi();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalle($calle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalle', array($calle));

        return parent::setCalle($calle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalle', array());

        return parent::getCalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntre($entre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntre', array($entre));

        return parent::setEntre($entre);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntre', array());

        return parent::getEntre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApartamento($apartamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApartamento', array($apartamento));

        return parent::setApartamento($apartamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getApartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApartamento', array());

        return parent::getApartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdificio($edificio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdificio', array($edificio));

        return parent::setEdificio($edificio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdificio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdificio', array());

        return parent::getEdificio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasa($casa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasa', array($casa));

        return parent::setCasa($casa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasa', array());

        return parent::getCasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonos($telefonos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonos', array($telefonos));

        return parent::setTelefonos($telefonos);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonos', array());

        return parent::getTelefonos();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', array($correo));

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', array());

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\NomencladorBundle\Entity\Empresa $empresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio(\NomencladorBundle\Entity\Municipio $municipio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', array($municipio));

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', array());

        return parent::getMunicipio();
    }

}
