<?php

namespace Proxies\__CG__\QuejasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Despacho extends \QuejasBundle\Entity\Despacho implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'id', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'asunto', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'fechaCreacion', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'fechaCulminacion', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'cliente');
        }

        return array('__isInitialized__', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'id', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'asunto', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'fechaCreacion', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'fechaCulminacion', '' . "\0" . 'QuejasBundle\\Entity\\Despacho' . "\0" . 'cliente');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Despacho $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsunto($asunto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsunto', array($asunto));

        return parent::setAsunto($asunto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsunto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsunto', array());

        return parent::getAsunto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCulminacion($fechaCulminacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCulminacion', array($fechaCulminacion));

        return parent::setFechaCulminacion($fechaCulminacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCulminacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCulminacion', array());

        return parent::getFechaCulminacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\QuejasBundle\Entity\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

}
